version: '3'
services:
  mssql:
    container_name: verdaccio
    image: verdaccio/verdaccio:4.6.0
    volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
      - ./data/conf:/verdaccio/conf
      - ./data/storage:/verdaccio/storage
      - ./data/plugins:/verdaccio/plugins
      - ./data/logs:/verdaccio/logs
    environment:
      - TZ=Asia/Taipei
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=http
#    network_mode:  "host"
    ports:
      - "4873:4873"
    networks:
      - node-network
networks:
  node-network:
    driver: bridge




